language: go
go:
- '1.3'
env:
  global:
  - PATH=$HOME/gopath/bin:$PATH
before_install:
- go get code.google.com/p/go.tools/cmd/cover
- go get github.com/golang/lint/golint
before_script:
- git config --global user.name Travis
- git config --global user.email travis@example.org
script:
- gofmt -l .
- golint .
- go test -cover -v ./...
